### ISSUE TITLE
How to compile in Windows ?

### ISSUE THREAD

**Issue by avogelba** [toor1245/cpu_features.NET#30]
I'm following documentation. I'm on Windows 10 / Visual Studio. However I'm unable to build.

-> has to be all_build:
c:\Github\cpu_features.NET>cmake --build cmake-build-release --target all_build -v
=> works!

-> building produces several errors:
 MSB3073: the command "setlocal
=> exit with 2 errors

However I managed to compile but the when using it, I get allot of exceptions.

Building also produces recursive directories: c:\Github\cpu_features.NET\src\CpuFeaturesDotNet\Native\Platforms\win\x86-64\Release\Release\Release\Release\Release\Release\Release\Release\Release\Release\Release\Release\Release\Release\Release\Release\Release\Release\..

**Comment by Dilorfin** [comment]
Hello, thanks for interest in cpu_features.NET! And sorry for not answering for a while...

You're right about `all_build` for VS. 

For now we have made several changes related to VS, so you can retry with up to date master/main branch.

Also could be tried running cmd as Admin and adding `--config=Release` to build command.
E.g.:
```shell
cmake -S. -Bcmake-build-release -A x64 -DCMAKE_BUILD_TYPE=Release
cmake --build cmake-build-release --target all_build -v --config Release
dotnet build "src/CpuFeaturesDotNet" -c Release --force --runtime win10-x64
dotnet test "tests" -c Release --runtime win10-x64
```

If it doesn't solve issue, please provide some more information:
- full building log (`cmake --build cmake-build-release --target all_build -v > errors.log` and send errors.log file)
- visual studio version
- os version
- if running `dotnet` from cmd please provide full command
